version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    networks:
      sofi_net:
        ipv4_address: 10.0.10.21

  kafka:
    image: wurstmeister/kafka:2.13-2.3.1
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      sofi_net:
        ipv4_address: 10.0.10.22

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "3306:3306"
    networks:
      sofi_net:
        ipv4_address: 10.0.10.23

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      sofi_net:
        ipv4_address: 10.0.10.24

  hive-metastore:
    image: apache/hive:2.3.10
    container_name: hive-metastore
    environment:
      HIVE_METASTORE_DB_TYPE: mysql
      HIVE_METASTORE_DB_HOST: mysql
      HIVE_METASTORE_DB_PORT: 3306
      HIVE_METASTORE_DB_NAME: metastore
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASS: hive
      SERVICE_NAME: metastore
    depends_on:
      - mysql
    ports:
      - "9083:9083"
    networks:
      sofi_net:
        ipv4_address: 10.0.10.25

  spark:
    image: bitnami/spark:3.3.0
    container_name: spark
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark
      SPARK_MASTER_PORT: 7077
    ports:
      - "4040:4040"
      - "7077:7077"
    depends_on:
      - kafka
      - minio
    networks:
      sofi_net:
        ipv4_address: 10.0.10.26

  spark-worker:
    image: bitnami/spark:3.3.0
    container_name: spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
    depends_on:
      - spark
    networks:
      sofi_net:
        ipv4_address: 10.0.10.27

  trino:
    image: trinodb/trino:373
    container_name: trino
    environment:
      - "HIVE_METASTORE_URI=thrift://hive-metastore:9083"
    ports:
      - "8080:8080"
    depends_on:
      - hive-metastore
    networks:
      sofi_net:
        ipv4_address: 10.0.10.28

networks:
  sofi_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.20/29

volumes:
  minio_data: